export const ALL_charges_default_values = {
  charges: [
    { charge_type: 'bedds', charge_amount: '' },
    { charge_type: 'Black Beeds', charge_amount: '' },
    { charge_type: 'Moti', charge_amount: '' },
    { charge_type: 'Diamond', charge_amount: '' },
    { charge_type: 'stone', charge_amount: '' },
    { charge_type: 'STONE', charge_amount: '' },
    { charge_type: 'DIA', charge_amount: '' },
  ],
};

export const huId_details_default_values = {
  huid: '',
  huid2: '',
  huid3: '',
  gram_option_1: 0,
  gram_option_2: 0,
};

export const diamond_details_default_values = {
  diamond_details: [
    {
      diamond_colour_clarity: 0,
      diamond_shape: 0,
      diamond_size_range: 0,
      diamond_colour: null,
      diamond_certificate: null,
      diamond_piece: 1,
      diamond_weight: 0,
      certificate_number: '',
      diamond_details: '',
      diamond_rate: 0,
      amount: 0,
    },
  ],
};

export const Purchase_details_default_values = {
  gold_wastage_charges: '',
  purchase_gold_rate: '',
  gold_purchase_making_charges: '',
  gold_purchase_value: '',
  gold_purchase_mrp: '',
  platinum_wastage_charges: '',
  purchase_platinum_rate: '',
  purchase_making_charges: '',
  purchase_platinum_value: '',
  purchase_platinum_mrp: '',
};

export const GemstoneFormDefaultValues = {
  main_type: 0,
  sub_type: 0,
  code: '',
  shape: 0,
  dimension: 0,
  carat_weight: '',
  rate: '',
  amount: '',
  certificate_charges: '',
  pieces: 0,
};

export const defaultValues = {
  item_code: '',
  quantity: 1,
  product_type: '',
  dealer: '',
  dealer_code: '',
  show_e_showroom: true,
  stock_type: '',
  metal_category: '',
  metal_category_name: '',
  box_counter: '',
  carat: '',
  remarks: '',
  design_code: '',
  certificate_number: '',
  gross_weight: '',
  less_weight: 0,
  platinum_net_weight: null,
  wastage_percentage: 0,
  wastage_gram: 0,
  wastage_type: 'percentage',
  value: 0,
  size: '',
  total_charges: 0,
  other_charges: [],
  huid_details: huId_details_default_values,
  huid_details_str: '',
  purchase_details: [],
  purchase_details_str: '',
  mrp: '',
  gemstone: false,
  gemstone_details_str: '',
  gemstone_details: [],
  media_ids: [],
  diamond_details: [],
  having_diamond: false,
};

export const defaultVariantValues = {
  item_code: '',
  show_e_showroom: true,
  metal_category: '',
  metal_category_name: '',
  metal_colour: '',
  carat: '',
  remarks: '',
  design_code: '',
  certificate_number: '',
  gross_weight: '',
  less_weight: 0,
  platinum_net_weight: null,
  wastage_percentage: 0,
  wastage_gram: 0,
  wastage_type: 'percentage',
  value: 0,
  size: '',
  total_charges: 0,
  other_charges: [],
  huid_details: huId_details_default_values,
  huid_details_str: '',
  purchase_details: [],
  purchase_details_str: '',
  mrp: '',
  gemstone: false,
  gemstone_details_str: '',
  gemstone_details: [],
  diamond_details: [],
  having_diamond: false,
};

// {
//   mainType: 'Diamond',
//   subType: '45',
//   code: '6465',
//   shape: 'Round',
//   dimension: '54',
//   carat_weight: 32,
//   rate: 32, // re
//   amount: 0,
//   certificate_charges: 0,
//   pcs: 0,
// },
// {
//   mainType: 'Diamond',
//   subType: '44',
//   code: '656',
//   shape: 'Round',
//   dimension: '54',
//   carat_weight: 4,
//   rate: 5,
//   amount: 0,
//   certChrg: 55,
//   pcs: 0,
// },
